version: '3.9'
services:
  cntnr_sport-events_nginx:
    image: 'nginx:latest'
    container_name: sport-events_nginx
    hostname: sport-events_nginx
    restart: "no"
    depends_on:
      - cntnr_sport-events_php
    links:
      - cntnr_sport-events_php
    ports:
      - '8858:80'
    volumes:
      - '../projects:/var/www/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
  cntnr_sport-events_php:
    build: php
    container_name: sport-events_php
    hostname: sport-events_php
    restart: "no"
    links:
      - cntnr_sport-events_mysql
      - cntnr_sport-events_phpmyadmin
      - cntnr_sport-events_redis
      - cntnr_sport-events_memcached
    volumes:
      - '../projects:/var/www/html'
      - './php/php.ini:/usr/local/etc/php/php.ini'
    ports:
      - '8859:9000'
  cntnr_sport-events_mysql:
    image: 'mysql:8.0'
    container_name: sport-events_mysql
    hostname: sport-events_mysql
    restart: "no"
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '8860:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  cntnr_sport-events_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sport-events_phpmyadmin
    hostname: sport-events_phpmyadmin
    restart: "no"
    depends_on:
      - cntnr_sport-events_mysql
    links:
      - cntnr_sport-events_mysql
    ports:
      - '8861:80'
    environment:
      - PMA_HOST=sport-events_mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - './phpmyadmin/php.ini:/usr/local/etc/php/php.ini'
  cntnr_sport-events_redis:
    image: 'redis:latest'
    container_name: sport-events_redis
    hostname: sport-events_redis
    restart: "no"
    command:
      - redis-server
      - '--appendonly'
      - 'yes'
    ports:
      - '8862:6379'
    volumes:
      - './redis/data:/data'
  cntnr_sport-events_memcached:
    image: 'memcached:latest'
    container_name: sport-events_memcached
    hostname: sport-events_memcached
    restart: "no"
    ports:
      - '8863:11211'